#!/bin/bash

TOTAL_FOLDERS=$(find ${1} -mindepth 0 -type d | wc -l)

function top_five_folders {
    COUNT=1
    [[ $TOTAL_FOLDERS -le 5 ]] && NUMBER_OF_DIR=${TOTAL_FOLDERS} || NUMBER_OF_DIR=5
    while [ ${COUNT} -le ${NUMBER_OF_DIR} ]; do
        TOP_FIVE_FOLDERS+="\t"${COUNT}
        TOP_FIVE_FOLDERS+=" - "
        TOP_FIVE_FOLDERS+=$(du -h ${1} | sort -rn | head -${COUNT} | tail +${COUNT} | awk '{print $2}')
        TOP_FIVE_FOLDERS+=", "
        TOP_FIVE_FOLDERS+=$(du -h ${1} | sort -rn | head -${COUNT} | tail +${COUNT} | awk '{print $1}')
        TOP_FIVE_FOLDERS+="\n"
        let COUNT++
    done 
}
